name: degub WF

on: 
  workflow_dispatch:

env: 
  USER_1: "foo-user"
  USER_2: "bar-user"

jobs:
  debug_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 01
        run: echo $USER_1 
      - name: Set USERNAME as USER_1
        run: echo "USERNAME=$USER_1" >> $GITHUB_ENV  # Permet de mettre une variable comme var d'env reutilisable dans le WF
      - name: Printing Username
        run: echo $USERNAME
      - name: Step 04
        run: echo $USER_2

